# Generated by Django 4.2.29 on 2026-03-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_admin_action_log_clear_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileshare',
            name='status',
            field=models.CharField(default='pending', max_length=16),
        ),
    ]
