# Generated by Django 4.2.29 on 2026-04-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_activity_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
